### ISSUE TITLE
关于预处理部分的问题

### ISSUE THREAD

**Issue by MooreAndMoore** [WHUIR/CARP#2]
最近我们在学习您的代码时感到困惑，希望您能帮助我们解答：
import util.AuxiliaryUtil中的AuxiliaryUtil是什么？我们不能找到或弄明白答案。
谢谢！

**Comment by MooreAndMoore** [comment]
我感觉是不是您少上传了两个文件呀？

**Comment by lichenliang-whu** [comment]
你好，相关代码已经更新。
